---
version: "3"
services:
  # The main TrackMyFish image
  trackmyfish:
    image: simondrake/trackmyfish:v1alpha1
    container_name: trackmyfish
    networks:
      - trackmyfish
    depends_on:
      - trackmyfish_db
    # Specify environment variables. The TMF_DB_* values should match
    # those in the trackmyfish_db image
    environment:
      - TMF_SERVER_PORT=8080
      - TMF_HTTP_PROXY_ENABLED=true
      - TMF_HTTP_PROXY_PORT=8443
      - TMF_DB_HOST=trackmyfish_db
      - TMF_DB_PORT=5432
      - TMF_DB_USERNAME=trackmyfish
      - TMF_DB_PASSWORD=supersecretpassword
      - TMF_DB_NAME=trackmyfish
    # Optionally, provide a config file.
    # You don't need to speify this and the environment variables
    # volumes:
      # - ./config.yaml:/config/config.yaml
    ports:
      - 8443:8443
    restart: unless-stopped
  # The database for TrackMyFish
  trackmyfish_db:
    image: postgres
    container_name: trackmyfish_db
    networks:
      - trackmyfish
    environment:
      - POSTGRES_PASSWORD=supersecretpassword
      - POSTGRES_USER=trackmyfish
      - POSTGRES_DB=trackmyfish
    volumes:
      - ${HOME}/trackmyfish/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
  # Runs the Database migrations for TrackMyFish. For example, it ensures all
  # the required tables exist.
  # See https://github.com/TrackMyFish/TrackMyFish/issues/1 for a known issue,
  # where the first run will fail
  trackmyfish_migrations:
    image: simondrake/trackmyfish_migrations:v1alpha1
    container_name: trackmyfish_migrations
    networks:
      - trackmyfish
    depends_on:
      - trackmyfish_db
    environment:
      - DATABASE_HOST=trackmyfish_db
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=trackmyfish
      - DATABASE_PASSWORD=supersecretpassword
      - DATABASE_NAME=trackmyfish

networks:
  trackmyfish:
